# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "35d29d13a770e7f47a25c82f7ecb3433"
name = "bulk-buying"
handle = "bulk-buying"
application_url = "https://aggressive-textile-refresh-records.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mypaperclip-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://aggressive-textile-refresh-records.trycloudflare.com/auth/callback",
  "https://aggressive-textile-refresh-records.trycloudflare.com/auth/shopify/callback",
  "https://aggressive-textile-refresh-records.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
